[[asciidoc-report-plugin]]
== AsciiDoc Report

The plugin records the results of executed rules (i.e. concepts and constraints).
At the end of the analysis phase http://www.asciidoctor[Asciidoctor] is used for rendering the input documents providing the rules to HTML documents. The rules blocks are identified and replaced by their status and results appended.
Furthermore, _++include::[]++_ directives are provided for embedding a summary about executed and imported rules.

By default, all rule files with the name `index.adoc` will be selected for rendering.
The report property `asciidoc.report.file.include` may be used to explicitly select files.
Files may be located in the rule directory of a project (e.g. `jqassistant/`, provided by plugins or in the directory specified by `asciidoc.report.rule.directory`


=== jQA Include Directives

The report may be enhanced by `jQA` include directives:

`jQA:Summary[concepts="...",importedConcepts="...",constraints="...",importedConstraints="..."]`::
Includes two summary tables containing executed rules, their description, status and severity.
The filter attributes are optional, if none is given all results are included.
  `concepts` and `constraints` refer to rules that are defined in the rendered AsciiDoc document(s).
  `importedConcepts` and `importedConstraints` refer to rules that are imported from plugins.
`jQA:Rules[concepts="...",constraints="..."]`::
  Embeds imported rules and their results identified by the specified filters. Both filter attributes are optional but at least one must be specified.
`jQA:ImportedRules[]`::
  `Deprecated` Renders descriptions for all imported rules which have been executed but which are not part of the document itself (i.e. provided by plugins).

TIP: Filter attributes are comma separated lists of id patterns and may contain wildcards, e.g. "layer:*, spring-\*:*".

.jqassistant/index.adoc
....
= My Project

This document describes architectural and design rules for My Project.

== Summary

\include::jQA:Summary[]

[[default]]
[role=group,includesGroups="..."]
== Project Specific Concepts & Constraints

...
project specific rules
...

== Common Spring Concepts & Constraints

\include::jQA:Rules[concepts="spring*:*",constraints="spring*:*"]
....

=== Configuration

The AsciiDoc Report plugin accepts several options that might be passed as report properties to jQAssistant:

[options="header"]
|===
| Property                            | Description                                                                                                        | Default
| asciidoc.report.directory           | Specifies the directory where the HTML files will be written                                                       | jqassistant/report/asciidoc
| asciidoc.report.rule.directory      | Specifies the directory where the Asciidoc files are located (optional)                                            |
| asciidoc.report.file.include        | A comma separated list of filter of AsciiDoc files to be included (optional)                                       |
| asciidoc.report.file.exclude        | A comma separated list of filter of AsciiDoc files to be excluded (optional)                                       |
|===

=== Distributing Of AsciiDoc Files In Plugins

AsciiDoc files may be distributed as part of plugins to allow sharing rules and reports between projects.

* Files must be located as classpath resources in the folder `/META-INF/jqassistant-rules` or sub-folders of it:
+
[source]
----
META-INF/
  |-jqassistant-plugin.xml
  |-jqassistant-rules/
    |-my-reports/
      |-index.adoc             // the document to be rendered
      |-included-rules.adoc    // a file included by index.adoc providing additional rules
      |-included-misc.adoc     // a file included by index.adoc without additional rules
----
+
TIP: Plugins should provide their reports in sub-folders (e.g. `/META-INF/jqassistant-rules/my-reports`) to avoid interferences with other plugins.
* AsciiDoc files may include AsciiDoc files located within the same plugin using relative paths:
+
[source,asciidoc]
.META-INF/jqassistant-rules/my-reports/index.adoc (i.e. rule file located with same plugin)
----
== My Report

\include::included-rules.adoc[]
\include::included-misc.adoc[]
----
+
* AsciiDoc files outside a plugin may include AsciiDoc files provided by the plugins using absolute paths (without `/META-INF/jqassistant-rules` prefix):
+
[source,asciidoc]
.jqassistant/index.adoc
----
== Project Rules

\include::/my-reports/included-rules.adoc[]
\include::/my-reports/included-misc.adoc[]
----
+
* AsciiDoc files containing rules must be registered in the plugin descriptor (note that `included-misc.adoc` is not registered)
+
[source,xml]
.META-INF/jqassistant-plugin.xml
----
<jqassistant-plugin>
    <rules>
        <resource>my-reports/index.adoc</resource>
        <resource>my-reports/included-rules.adoc</resource>
    </rules>
</jqassistant-plugin>
----
* The AsciiDoc files may embed PlantUML diagrams:
+
[source,asciidoc]
....
= Component Diagram

[plantuml]
.Building Block Diagram
----
@startuml
component "Component 1" as c1
component "Component 2" as c2

c1 --> c2 : Depends On
@enduml
----
....
NOTE: Embedding images or other resources into plugins that can be referenced by AsciiDoc files is currently not supported.
