= jQAssistant AsciiDoc Report Plugin

This is the https://asciidoctor.org/[AsciiDoc^] report plugin for https://jqassistant.org[jQAssistant^].

After an analysis https://asciidoctor.org[Asciidoctor] it renders the input documents that provided rules to HTML documents.

It enriches the output by the status of executed rules as well as their results as tables, embedded diagrams or external links (e.g. CSV).

Furthermore, it provides _++include::[]++_ directives for embedding the results of imported rules and summary tables.

For more information on jQAssistant see https://jqassistant.org[^].

== Using the jqassistant-asciidoc-report-plugin

NOTE:: Starting from jqassistant-asciidoc-report-plugin v2.0.0, the AsciiDoc-Report-Plugin resides under jqassistant-plugin.
Therefore, not only the repository location changed but also group id and artifact id were adapted from `com.buschmais.jqassistant.plugin:asciidoc-report` to `org.jqassistant.plugin:jqassistant-asciidoc-report-plugin`.

NOTE:: From jQAssistant v2.0.0 onwards, it is not part of the core distribution anymore and a manual configuration as shown below is required.

[source, yaml]
..jqassistant.yml
----
jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin <1>
      artifact-id: jqassistant-asciidoc-report-plugin
      version: ${jqassistant.asciidoc-report-plugin.version}
----
<1> Dependency to the AsciiDoc Report plugin

== Changelog

=== 2.0.0

- Removed Plug-In from the jQAssistant Core Distribution to jqassistant-plugin
-- Group and Artifact Id changed to `org.jqassistant.plugin:jqassistant-asciidoc-report-plugin`
-- Migrated Asciidoc Rule Parser from jQAssistant Core distribution to this plugin
- Extracted PlantUML reports to a separate https://github.com/jqassistant-plugin/jqassistant-plantuml-report-plugin[PlantUML report plugin]

=== 1.12.2

- Fixed a problem where Asciidoc reports provided by plugins could not be rendered if the plugins were loaded from `.jqassistant.yml` configurations

=== 1.12.1

- Added sorting of rules included by `jQA:Rules` (alphabetically by rule id)
- Added rule id to hover of rule result
- Fixed escaping of node and relationship labels in component diagrams

=== 1.12.0

- Support the status `WARNING` in the summary table and rule results
- Added support for rendering PlantUML using the Eclipse Layout Kernel (Elk)
- JDOT was replaced by Smetana for rendering the PlantUML diagram when no local GraphViz installation is used.
- Delayed initialization of PlantUML to avoid unnecessary messages if GraphViz is not installed
- Removed deprecation of `asciidoc.report.rule.directory`

=== 1.11.0

- Added support for rendering AsciiDoc files as reports which are provided by plugins and contain rules.
- Deprecated the report property `asciidoc.report.rule.directory`, it will be removed in future versions.

=== 1.9.0

- The PlantUML diagram plugin now automatically selects GraphViz (prefered) or JDOT for rendering if not explicitly configured

=== 1.8.0

- Include AsciiDoc Report plugin into jQAssistant main project. Note that for upgrading to 1.8 any existing dependency to the AsciiDoc Report plugin from the contrib area must be removed
- Renamed properties `asciidoc.report.plantuml.format` & `asciidoc.report.plantuml.rendermode` to `plantuml.report.format` & `plantuml.report.rendermode`